### ISSUE TITLE
is it possible not to try to restart interfaces after configuration?

### ISSUE THREAD

**Issue by ashak** [dresden-weekly/ansible-network-interfaces#53]
I see there's a variable network_allow_service_restart, but this only seems to cover part of restarting things after interfaces are configured.

Is it (or could it be) possible to also have a way to not to try and restart the interfaces after their configuration is put in place?

The task i'm thinking of specifically is 'network restart interface command'. I want to not run this task at all and then simply reboot the machine afterwards.

**Comment by arBmind** [comment]
as documented in the [defaults/main.yml](https://github.com/dresden-weekly/ansible-network-interfaces/blob/develop/defaults/main.yml#L17) you might set `network_restart_method` to `nothing`. So nothing is done.

**Comment by arBmind** [comment]
To elaborate a bit more... We have two situations.

1. When applied first, we change the main interface description, to include all our details from the directory. In order to make this effective we use the `network_allow_service_restart`. You set this to `no` and nothing will happen in this case.

2. When only one of the interfaces is changed later, just the individual interface requires a restart. You can control how this is done with the `network_restart_method`. The content of this variable is used to index the `network_interface_restart_commands` hash. If it is `service` we use the `service` module of Ansible.

**Comment by ashak** [comment]
Thanks for this, I will try it out. I had not spotted the defaults/main.yml file.
